services:
  label-this:
    image: app
    build: .
    ports:
      - 3000:3000
    # for hot reloading
    # volumes:
    #   - ./components:/app/components
    #   - ./hooks:/app/hooks
    #   - ./pages:/app/pages
    #   - ./prisma:/app/prisma
    #   - ./public:/app/public
    #   - ./styles:/app/styles
  postgres:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hello-there
    ports:
      - '5432:5432'
